### PR TITLE
fix(app-nav-bar): pass a str to Avatar, no drawer menu if no menu items

### LINKED ISSUE #3348: App Nav Bar - mainNav should hide if false or null array
## Current Behavior
In the AppNavBar Component, the mainNav if the value is not give or empty array, the list icon appears and on performing click event on icon it fails and asks for avatar and other components.

**Icon Screenshot** - list icon
image

**OnClick Event Screenshot**
image

## Expected Behavior
In the AppNavBar Component, the mainNav if the value is empty array, the list icon should appear but event should not happen.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.72.0 |
| React   |  16.13.1   |
| Browser |  Chrome/ Firefox/ Safari |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

### PR DESCRIPTION
**Pull request by nadiia**
Fixes #3348 

#### Description

It errored out when no username was provided.

#### Scope
Patch: Bug Fix

### CODE REVIEW

File: src/app-nav-bar/user-menu/user-menu.js [hunk 1]
```diff
@@ -35,7 +35,7 @@ export default function UserMenu(props: AppNavBarPropsT) {
       triggerType={TRIGGER_TYPE.click}
     >
       <Button overrides={{BaseButton: {component: StyledUserMenuButton}}}>
-        <Avatar name={username} src={userImgUrl} size={'32px'} />
+        <Avatar name={username || ''} src={userImgUrl} size={'32px'} />
```
Comment (gergelyke) [inline src/app-nav-bar/user-menu/user-menu.js:38]: in the case where the username is `undefined`, do we want to have an empty string as the prop value? or should we remove the prop entirely?

Comment (nadiia) [reply src/app-nav-bar/user-menu/user-menu.js:38]: `name` is a required prop in `Avatar` (could be replaced with custom `initials`) and it doesn't provide a default value, therefore, errors out.
