### PR TITLE
fix(radio): margin considering horizontal/vertical/rtl/description

### LINKED ISSUE #2364: [Radio] UI distorts when align="horizontal"
## Current Behavior
UI distorts when align="horizontal" 

Steps to Reproduce: 

- Open - [https://baseweb.design/components/radio/](https://baseweb.design/components/radio/)
- Select `align="horizontal"`

image

## Expected Behavior
UI should render properly

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.21.1  |
| browser |     Chrome    |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

### PR DESCRIPTION
**Pull request by foodforarabbit**
Fixes #2364 
#### Description

forked solution off https://github.com/uber/baseweb/pull/2375 (so this PR makes that one redundant, I wasn't sure how to add changes to someone else's PR, and it seemed like making a PR into his feature branch was a very circular path)

- Give Radio component align prop since it needs to know how to arrange itself based on how it is going to be aligned with other Radio components (Normally I'd just do a wrapper around RadioGroup children, but I guess there are advantages to leaving the children unwrapped. Also I guess Radio needs to know align to arrange itself with description anyway)
- fix margin issues with Radio consider whether it has description or not, the alignment, and the theme.direction (e.g. rtl)
- fixed margin issues with Description with the same considerations.

#### Scope

- [x] Patch: Bug Fix
- [ ] Minor: New Feature
- [ ] Major: Breaking Change

### CODE REVIEW

File: src/radio/styled-components.js [hunk 1]
```diff
@@ -205,12 +216,31 @@ export const Input = styled('input', {
...
+  if ($theme.direction === 'rtl') {
+    if (marginBefore === 'Left') {
+      marginBefore = 'Right';
+    } else if (marginBefore === 'Right') {
+      marginBefore = 'Left';
+    }
+  }
+  let marginAfter = 'Right';
+  if ($theme.direction === 'rtl') {
+    if (marginAfter === 'Left') {
```
Comment (foodforarabbit) [inline src/radio/styled-components.js]: This could be done in a utility function or the variable could be assigned in a slicker way but I like the clarity and simplicity of rtl swap. Let me know if we want this to be more terse though and I can rewrite it.

Comment (foodforarabbit) [reply src/radio/styled-components.js]: actually now that I see it written out I'm going to go with the shorter version haha
