### PR TITLE
fix(ts): fix some TS errors

### LINKED ISSUE #3290: Import declaration conflicts with local declaration of 'SIZE'.
There's a naming conflict in `button-group/index.d.ts` and it's causing TS errors for us:

```
import {SHAPE, SIZE, KIND} from '../button';

...

export interface SIZE {
  compact: 'compact';
  default: 'default';
  large: 'large';
  mini: 'mini';
}
```

## Current Behavior

Typecheck fails with:
```
> tsc --build tsconfig.json

node_modules/baseui/button-group/index.d.ts:3:16 - error TS2440: Import declaration conflicts with local declaration of 'SIZE'.

3 import {SHAPE, SIZE, KIND} from '../button';
                 ~~~~
```

## Expected Behavior

There should be no conflict

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.73.2  |
| React   | 16.13.1 |
| browser | Firefox 76.0b8 (64-bit) |
| npm | 6.13.4 |
| Node | v12.16.1 |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

### PR DESCRIPTION
**Pull request by amarinov**
Fixes #3290 

#### Description

There are several Typescript errors that can not be seen using `yarn tsc`, because when `skipLibCheck` is being passed, errors from all index.d.ts files are ignored. This diff fixes most of them.

```sh
baseweb % npx tsc   
node_modules/@types/jest/index.d.ts:531:31 - error TS2314: Generic type 'Matchers<R, T>' requires 2 type argument(s).

531         <T = any>(actual: T): Matchers<T>;
                                  ~~~~~~~~~~~

node_modules/@types/jest/index.d.ts:606:15 - error TS2428: All declarations of 'Matchers' must have identical type parameters.

606     interface Matchers<R> {
                  ~~~~~~~~

node_modules/@types/jest/index.d.ts:618:14 - error TS2314: Generic type 'Matchers<R, T>' requires 2 type argument(s).

618         not: Matchers<R>;
                 ~~~~~~~~~~~

node_modules/@types/jest/index.d.ts:631:19 - error TS2314: Generic type 'Matchers<R, T>' requires 2 type argument(s).

631         resolves: Matchers<Promise<R>>;
                      ~~~~~~~~~~~~~~~~~~~~

node_modules/@types/jest/index.d.ts:636:18 - error TS2314: Generic type 'Matchers<R, T>' requires 2 type argument(s).

636         rejects: Matchers<Promise<R>>;
                     ~~~~~~~~~~~~~~~~~~~~

node_modules/@types/testing-library__jest-dom/index.d.ts:12:15 - error TS2428: All declarations of 'Matchers' must have identical type parameters.

12     interface Matchers<R, T> {
                 ~~~~~~~~

node_modules/next/dist/next-server/server/next-server.d.ts:130:17 - error TS1056: Accessors are only available when targeting ECMAScript 5 and higher.

130     private get _isLikeServerless();
                    ~~~~~~~~~~~~~~~~~

node_modules/next/dist/next-server/server/next-server.d.ts:130:17 - error TS7033: Property '_isLikeServerless' implicitly has type 'any', because its get accessor lacks a return type annotation.

130     private get _isLikeServerless();
                    ~~~~~~~~~~~~~~~~~

node_modules/next/types/index.d.ts:8:21 - error TS2307: Cannot find module '../lib/load-env-config'.

8 import { Env } from '../lib/load-env-config'
                      ~~~~~~~~~~~~~~~~~~~~~~~~

src/app-nav-bar/index.d.ts:9:16 - error TS2694: Namespace '"/Users/sasho/Uber/baseweb/node_modules/@types/react/index.d.ts"' has no exported member 'AbstractComponent'.

9   icon?: React.AbstractComponent<any>;
                 ~~~~~~~~~~~~~~~~~

src/app-nav-bar/index.d.ts:14:23 - error TS2694: Namespace '"/Users/sasho/Uber/baseweb/node_modules/@types/react/index.d.ts"' has no exported member 'AbstractComponent'.

14   navExitIcon?: React.AbstractComponent<any>;
                         ~~~~~~~~~~~~~~~~~

src/app-nav-bar/index.d.ts:19:16 - error TS2694: Namespace '"/Users/sasho/Uber/baseweb/node_modules/@types/react/index.d.ts"' has no exported member 'AbstractComponent'.

19   icon?: React.AbstractComponent<any>;
                  ~~~~~~~~~~~~~~~~~

src/app-nav-bar/index.d.ts:30:69 - error TS2304: Cannot find name 'mixed'.

30   onNavItemSelect: (params: {item: MainNavItemT | UserNavItemT}) => mixed;
                                                                       ~~~~~

src/app-nav-bar/index.d.ts:35:2 - error TS1036: Statements are not allowed in ambient contexts.

35 };
    ~

src/button-group/index.d.ts:3:16 - error TS2440: Import declaration conflicts with local declaration of 'SIZE'.

3 import {SHAPE, SIZE, KIND} from '../button';
                 ~~~~

src/card/index.d.ts:3:27 - error TS7016: Could not find a declaration file for module './types.js'. '/Users/sasho/Uber/baseweb/src/card/types.js' implicitly has an 'any' type.

3 import {ImagePropsT} from './types.js';
                            ~~~~~~~~~~~~

src/pagination/index.d.ts:5:9 - error TS2440: Import declaration conflicts with local declaration of 'SIZE'.

5 import {SIZE} from '../input';
          ~~~~


Found 17 errors.

```

### CODE REVIEW

File: src/button-group/index.d.ts [hunk 1]
```diff
@@ -3,6 +3,8 @@ import {StyledFn, StyletronComponent} from 'styletron-react';
 import {SHAPE, SIZE, KIND} from '../button';
 import {Override} from '../overrides';
 
+export {SIZE};
```
Comment (sandgraham) [inline src/button-group/index.d.ts:6]: question: why is this change (and the one in pagination) required?

Comment (amarinov) [reply src/button-group/index.d.ts:6]: There is a conflict of SIZE constants within those files:
```
src/button-group/index.d.ts:3:16 - error TS2440: Import declaration conflicts with local declaration of 'SIZE'.

3 import {SHAPE, SIZE, KIND} from '../button';
```

I've removed the declaration of `SIZE` constant at the bottom of button-group/index.d.ts and pagination/index.d.ts files and I've reexported it from 'button' module ( no need to redeclare it really ).

**Comment by jonjrodriguez** [comment]
Yeah, we still have some issues where we can't upgrade baseweb since we get the TS error mentioned in https://github.com/uber/baseweb/issues/3290:

`node_modules/baseui/button-group/index.d.ts(3,16): error TS2440: Import declaration conflicts with local declaration of 'SIZE'.`
